"""Initial migration: User, Session, Health, Workout, Nutrition, Coaching models

Revision ID: b72667ea0290
Revises: 
Create Date: 2025-12-14 18:37:01.002861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b72667ea0290'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.Enum('compound', 'isolation', 'cardio', 'flexibility', 'core', 'plyometric', 'martial_arts', name='exercisecategory', native_enum=False), nullable=False),
    sa.Column('muscle_groups', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('equipment_needed', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('difficulty_level', sa.Enum('beginner', 'intermediate', 'advanced', 'expert', name='difficultylevel', native_enum=False), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('tips', sa.Text(), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercise_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercise_definitions_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercise_definitions_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', 'coach', name='userrole', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('profile_photo_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('coaching_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('topics', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('discussion_notes', sa.Text(), nullable=True),
    sa.Column('coach_feedback', sa.Text(), nullable=True),
    sa.Column('action_items', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('next_session_date', sa.Date(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completion_notes', sa.Text(), nullable=True),
    sa.Column('user_rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coaching_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_coaching_sessions_coach_date', ['coach_id', 'session_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_coaching_sessions_coach_id'), ['coach_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coaching_sessions_session_date'), ['session_date'], unique=False)
        batch_op.create_index('ix_coaching_sessions_user_date', ['user_id', 'session_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_coaching_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('health_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recorded_date', sa.Date(), nullable=False),
    sa.Column('weight_lbs', sa.Float(), nullable=True),
    sa.Column('body_fat_percentage', sa.Float(), nullable=True),
    sa.Column('muscle_mass_lbs', sa.Float(), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('waist_inches', sa.Float(), nullable=True),
    sa.Column('chest_inches', sa.Float(), nullable=True),
    sa.Column('left_arm_inches', sa.Float(), nullable=True),
    sa.Column('right_arm_inches', sa.Float(), nullable=True),
    sa.Column('left_thigh_inches', sa.Float(), nullable=True),
    sa.Column('right_thigh_inches', sa.Float(), nullable=True),
    sa.Column('hips_inches', sa.Float(), nullable=True),
    sa.Column('neck_inches', sa.Float(), nullable=True),
    sa.Column('resting_heart_rate', sa.Integer(), nullable=True),
    sa.Column('blood_pressure_systolic', sa.Integer(), nullable=True),
    sa.Column('blood_pressure_diastolic', sa.Integer(), nullable=True),
    sa.Column('energy_level', sa.Integer(), nullable=True),
    sa.Column('mood', sa.Integer(), nullable=True),
    sa.Column('sleep_quality', sa.Integer(), nullable=True),
    sa.Column('stress_level', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'recorded_date', name='uq_user_health_date')
    )
    with op.batch_alter_table('health_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_health_metrics_recorded_date'), ['recorded_date'], unique=False)
        batch_op.create_index('ix_health_metrics_user_date', ['user_id', 'recorded_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_metrics_user_id'), ['user_id'], unique=False)

    op.create_table('meal_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('meal_date', sa.Date(), nullable=False),
    sa.Column('meal_time', sa.Time(), nullable=True),
    sa.Column('meal_type', sa.Enum('breakfast', 'lunch', 'dinner', 'snack', 'pre_workout', 'post_workout', 'other', name='mealtype', native_enum=False), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('protein_g', sa.Float(), nullable=True),
    sa.Column('carbs_g', sa.Float(), nullable=True),
    sa.Column('fat_g', sa.Float(), nullable=True),
    sa.Column('fiber_g', sa.Float(), nullable=True),
    sa.Column('sugar_g', sa.Float(), nullable=True),
    sa.Column('sodium_mg', sa.Integer(), nullable=True),
    sa.Column('water_oz', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('foods', sa.Text(), nullable=True),
    sa.Column('recipe_name', sa.String(length=200), nullable=True),
    sa.Column('adherence_to_plan', sa.Enum('perfect', 'good', 'fair', 'poor', 'off_plan', name='adherencelevel', native_enum=False), nullable=True),
    sa.Column('planned_meal', sa.Boolean(), nullable=False),
    sa.Column('satisfaction', sa.Integer(), nullable=True),
    sa.Column('hunger_before', sa.Integer(), nullable=True),
    sa.Column('hunger_after', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meal_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_logs_meal_date'), ['meal_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_logs_meal_type'), ['meal_type'], unique=False)
        batch_op.create_index('ix_meal_logs_user_date', ['user_id', 'meal_date'], unique=False)
        batch_op.create_index('ix_meal_logs_user_date_type', ['user_id', 'meal_date', 'meal_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_logs_user_id'), ['user_id'], unique=False)

    op.create_table('progress_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('photo_date', sa.Date(), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=False),
    sa.Column('photo_type', sa.Enum('front', 'side', 'back', 'flex', 'comparison', 'other', name='phototype', native_enum=False), nullable=False),
    sa.Column('weight_lbs', sa.Float(), nullable=True),
    sa.Column('body_fat_percentage', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('progress_photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_progress_photos_photo_date'), ['photo_date'], unique=False)
        batch_op.create_index('ix_progress_photos_user_date', ['user_id', 'photo_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_progress_photos_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_progress_photos_user_type', ['user_id', 'photo_type'], unique=False)

    op.create_table('user_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal_type', sa.Enum('weight_loss', 'muscle_gain', 'strength', 'endurance', 'flexibility', 'skill', 'habit', 'nutrition', 'other', name='goaltype', native_enum=False), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('target_unit', sa.String(length=50), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('progress_percentage', sa.Float(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('active', 'completed', 'paused', 'abandoned', name='goalstatus', native_enum=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('milestones', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_goals_goal_type'), ['goal_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_goals_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_user_goals_user_status', ['user_id', 'status'], unique=False)
        batch_op.create_index('ix_user_goals_user_type', ['user_id', 'goal_type'], unique=False)

    op.create_table('user_sessions',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revocation_reason', sa.String(length=200), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('browser', sa.String(length=100), nullable=True),
    sa.Column('os', sa.String(length=100), nullable=True),
    sa.Column('remember_me', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_user_sessions_expires', ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sessions_is_active'), ['is_active'], unique=False)
        batch_op.create_index('ix_user_sessions_user_active', ['user_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('workout_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('session_type', sa.Enum('strength', 'cardio', 'flexibility', 'martial_arts', 'sports', 'recovery', 'mixed', name='sessiontype', native_enum=False), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('program_phase', sa.String(length=100), nullable=True),
    sa.Column('week_number', sa.Integer(), nullable=True),
    sa.Column('day_number', sa.Integer(), nullable=True),
    sa.Column('intensity', sa.Integer(), nullable=True),
    sa.Column('fatigue', sa.Integer(), nullable=True),
    sa.Column('soreness', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('coach_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workout_sessions_session_date'), ['session_date'], unique=False)
        batch_op.create_index('ix_workout_sessions_user_date', ['user_id', 'session_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('exercise_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_session_id', sa.Integer(), nullable=False),
    sa.Column('exercise_definition_id', sa.Integer(), nullable=True),
    sa.Column('exercise_name', sa.String(length=200), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('weight_lbs', sa.Float(), nullable=True),
    sa.Column('rest_seconds', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('distance_miles', sa.Float(), nullable=True),
    sa.Column('form_quality', sa.Integer(), nullable=True),
    sa.Column('rpe', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exercise_definition_id'], ['exercise_definitions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workout_session_id'], ['workout_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercise_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercise_logs_exercise_definition_id'), ['exercise_definition_id'], unique=False)
        batch_op.create_index('ix_exercise_logs_session', ['workout_session_id', 'order_index'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercise_logs_workout_session_id'), ['workout_session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercise_logs_workout_session_id'))
        batch_op.drop_index('ix_exercise_logs_session')
        batch_op.drop_index(batch_op.f('ix_exercise_logs_exercise_definition_id'))

    op.drop_table('exercise_logs')
    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_sessions_user_id'))
        batch_op.drop_index('ix_workout_sessions_user_date')
        batch_op.drop_index(batch_op.f('ix_workout_sessions_session_date'))

    op.drop_table('workout_sessions')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_user_id'))
        batch_op.drop_index('ix_user_sessions_user_active')
        batch_op.drop_index(batch_op.f('ix_user_sessions_is_active'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_expires_at'))
        batch_op.drop_index('ix_user_sessions_expires')
        batch_op.drop_index(batch_op.f('ix_user_sessions_created_at'))

    op.drop_table('user_sessions')
    with op.batch_alter_table('user_goals', schema=None) as batch_op:
        batch_op.drop_index('ix_user_goals_user_type')
        batch_op.drop_index('ix_user_goals_user_status')
        batch_op.drop_index(batch_op.f('ix_user_goals_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_goals_goal_type'))

    op.drop_table('user_goals')
    with op.batch_alter_table('progress_photos', schema=None) as batch_op:
        batch_op.drop_index('ix_progress_photos_user_type')
        batch_op.drop_index(batch_op.f('ix_progress_photos_user_id'))
        batch_op.drop_index('ix_progress_photos_user_date')
        batch_op.drop_index(batch_op.f('ix_progress_photos_photo_date'))

    op.drop_table('progress_photos')
    with op.batch_alter_table('meal_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_logs_user_id'))
        batch_op.drop_index('ix_meal_logs_user_date_type')
        batch_op.drop_index('ix_meal_logs_user_date')
        batch_op.drop_index(batch_op.f('ix_meal_logs_meal_type'))
        batch_op.drop_index(batch_op.f('ix_meal_logs_meal_date'))

    op.drop_table('meal_logs')
    with op.batch_alter_table('health_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_health_metrics_user_id'))
        batch_op.drop_index('ix_health_metrics_user_date')
        batch_op.drop_index(batch_op.f('ix_health_metrics_recorded_date'))

    op.drop_table('health_metrics')
    with op.batch_alter_table('coaching_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coaching_sessions_user_id'))
        batch_op.drop_index('ix_coaching_sessions_user_date')
        batch_op.drop_index(batch_op.f('ix_coaching_sessions_session_date'))
        batch_op.drop_index(batch_op.f('ix_coaching_sessions_coach_id'))
        batch_op.drop_index('ix_coaching_sessions_coach_date')

    op.drop_table('coaching_sessions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('exercise_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercise_definitions_name'))
        batch_op.drop_index(batch_op.f('ix_exercise_definitions_category'))

    op.drop_table('exercise_definitions')
    # ### end Alembic commands ###
