"""Add Document model

Revision ID: ed9eaadc6a3f
Revises: e1f2a3b4c5d6
Create Date: 2026-01-10 15:23:27.019113

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ed9eaadc6a3f'
down_revision = 'e1f2a3b4c5d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('document_type', sa.Enum('WORKOUT_PLAN', 'MEAL_PLAN', 'PROGRESS_REPORT', 'FITNESS_ROADMAP', 'ANALYSIS', 'COACHING_NOTES', 'EDUCATIONAL', 'CUSTOM', name='documenttype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation_logs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index('ix_documents_user_archived', ['user_id', 'is_archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_documents_user_slug', ['user_id', 'slug'], unique=True)
        batch_op.create_index('ix_documents_user_type', ['user_id', 'document_type'], unique=False)

    with op.batch_alter_table('behavior_definitions', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('health', 'fitness', 'nutrition', 'learning', 'productivity', 'wellness', 'custom', name='behaviorcategory', native_enum=False),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('behavior_definitions', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.Enum('health', 'fitness', 'nutrition', 'learning', 'productivity', 'wellness', 'custom', name='behaviorcategory', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index('ix_documents_user_type')
        batch_op.drop_index('ix_documents_user_slug')
        batch_op.drop_index(batch_op.f('ix_documents_user_id'))
        batch_op.drop_index('ix_documents_user_archived')
        batch_op.drop_index(batch_op.f('ix_documents_conversation_id'))

    op.drop_table('documents')
    # ### end Alembic commands ###
